#!/usr/bin/env python3
"""Embed binary files as C byte arrays: embed.py OUT.h name=path [name=path ...]

Fonts (and any future blobs) are baked into the PE so teidraw ships as a
single self-contained exe — no fonts dir to lose track of.
"""
import sys


def main():
    out = sys.argv[1]
    chunks = []
    for spec in sys.argv[2:]:
        name, path = spec.split("=", 1)
        data = open(path, "rb").read()
        lines = []
        for i in range(0, len(data), 20):
            lines.append(",".join(str(b) for b in data[i : i + 20]))
        chunks.append(
            f"static const unsigned char {name}[] = {{\n"
            + ",\n".join(lines)
            + f"\n}};\nstatic const unsigned int {name}_len = {len(data)};\n"
        )
    with open(out, "w") as f:
        f.write("// generated by tools/embed.py — do not edit\n#pragma once\n")
        f.write("\n".join(chunks))
    print(f"embedded {len(sys.argv) - 2} blobs -> {out}")


if __name__ == "__main__":
    main()
